# Site settings
baseurl = "http://ma-al.github.io/hugo-test"
languageCode = "en-us"
title = "Hugrid - Quack Test"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"

[params]
    # Meta
    title = "Test test quack quack. hugrid!"
    subtitle = "A kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on."
    author = "Pavel Kanyshev"
    description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts"
    
    # Body background color
	bodybgcolor = "#f9f9f9"
    
    # Preview container button text
    buttontext = "Get the theme"
    
    # Footer text
    footertext = "Made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [Hugo](http://gohugo.io) and [me](https://github.com/aerohub)"
